package shared

import "testing"

// Expected outputs generated by running the Node redactText (packages/shared/src/redact.ts) — the Go port replaces
// the look-behind/look-ahead phone regex by a hand matcher and must agree on all of these.
func TestRedactTextMatchesNode(t *testing.T) {
	vectors := map[string]string{
		"call 0912345678 now":          "call [REDACTED:phone] now",
		"call +84 912 345 678":         "call [REDACTED:phone]",
		"x20912345678y":                "x20912345678y",
		"x 091234567890 y":             "x 091234567890 y",
		"0912.345.678":                 "[REDACTED:phone]",
		"short 091234":                 "short 091234",
		"84912345678":                  "[REDACTED:phone]",
		"+84912345678 and 0987654321.": "[REDACTED:phone] and [REDACTED:phone].",
		"0 9 1 2 3 4 5 6 7 8 9 end":    "[REDACTED:phone] end",
		"0 9 1 2 3 4 5 6 7 8 9 0 1 2":  "[REDACTED:card]",
		"tel:0912-345-678;":            "tel:[REDACTED:phone];",
		"0912345678":                   "[REDACTED:phone]",
		"a0912345678":                  "a[REDACTED:phone]",
		"09123456789":                  "[REDACTED:phone]",
		"091234567":                    "091234567",
		"+840912345678":                "[REDACTED:phone]",
		"8491234567 8":                 "[REDACTED:phone]",
		"mail a.b@x.vn 0901234567 tok eyJhbGciOiJI.eyJzdWIiOiIx.abcdefghijk end": "mail [REDACTED:email] [REDACTED:phone] tok [REDACTED:jwt] end",
		"Bearer abcdefghijklmnop1 and bearer short":                              "Bearer [REDACTED] and bearer short",
		"card 4111 1111 1111 1111 ok":                                            "card [REDACTED:card]ok",
		"0912345678 0912345678":                                                  "[REDACTED:phone] [REDACTED:phone]",
		"0912 345 678 9":                                                         "[REDACTED:phone]",
		"+84 912 345 6789":                                                       "[REDACTED:phone]",
		"0.912.345.678.9":                                                        "[REDACTED:phone]",
	}
	for in, want := range vectors {
		if got := RedactText(in); got != want {
			t.Errorf("RedactText(%q) = %q, want %q", in, got, want)
		}
	}
}
