package audit

import (
	"encoding/json"
	"strings"
	"testing"
)

// Vectors generated by the Node implementation (services/api/src/audit.ts canon()+digest) — the hash chain must be byte-compatible.
func TestDigestMatchesNode(t *testing.T) {
	var detail any
	dec := json.NewDecoder(strings.NewReader(`{"z":1,"a":[1.5,null,"ü😀",true],"ä":{"b":false,"n":0.000001,"m":1e-7,"big":1e21,"neg":-12},"Z":"x","":"empty","10":1,"9":2}`))
	dec.UseNumber()
	if err := dec.Decode(&detail); err != nil {
		t.Fatal(err)
	}
	wantCanon := `{"":"empty","10":1,"9":2,"Z":"x","a":[1.5,null,"ü😀",true],"z":1,"ä":{"b":false,"big":1e+21,"m":1e-7,"n":0.000001,"neg":-12}}`
	if got := canon(detail); got != wantCanon {
		t.Fatalf("canon:\n got %s\nwant %s", got, wantCanon)
	}
	actor := "5f1c2d3e-0000-4000-8000-000000000001"
	got := digest(Genesis, "2026-01-02T03:04:05.678Z", &actor, "a \"q\" <é>   \n\t\u0001", "x.y", "ticket", "i", detail)
	if want := "a2a51789e016a09397b24594b067b23d45d6afd701579460dedb91ab8ae2d440"; got != want {
		t.Fatalf("digest %s want %s", got, want)
	}
	got2 := digest(strings.Repeat("a", 64), "2026-12-31T23:59:59.000Z", nil, "system", "notify.dead", "ticket", "abc", map[string]any{})
	if want := "c248b95a54565e0f4dafb808751a2b8728e54271099e138f1be4b5a61e8492d5"; got2 != want {
		t.Fatalf("digest2 %s want %s", got2, want)
	}
}
